# Generated by Django 6.0.2 on 2026-02-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('EQUIPMENT', 'Equipment'), ('SUPPLIES', 'Supplies'), ('OTHER', 'Other')], default='ELECTRONICS', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('access_level', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='FACULTY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
