# Generated by Django 6.0.2 on 2026-02-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='access_level',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
    ]
