# Generated by Django 6.0.2 on 2026-02-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_change_default_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
    ]
