# Generated by Django 6.0.2 on 2026-02-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_is_returnable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='borrow_duration',
            field=models.PositiveIntegerField(blank=True, help_text='How long a borrower can keep this item', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='borrow_duration_unit',
            field=models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days'), ('MONTHS', 'Months')], default='DAYS', max_length=10),
        ),
    ]
