# Generated by Django 6.0.2 on 2026-02-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_borrow_duration_item_borrow_duration_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='borrow_duration_unit',
            field=models.CharField(choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days'), ('MONTHS', 'Months')], default='DAYS', max_length=10),
        ),
    ]
