# Generated by Django 6.0.2 on 2026-02-25 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_borrow_duration_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='maintenance_eta',
            field=models.DateTimeField(blank=True, help_text='Estimated return-to-service date', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the status was last changed', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, help_text='Who last changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='status_note',
            field=models.TextField(blank=True, default='', help_text='Reason or note for current status'),
        ),
    ]
