# Generated by Django 6.0.2 on 2026-04-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_maintenance_eta_item_status_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', help_text='Item importance: LOW (consumables), MEDIUM (standard), HIGH (fragile/expensive)', max_length=10),
        ),
    ]
