# Generated by Django 6.0.2 on 2026-02-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for overdue returns'),
        ),
        migrations.AddField(
            model_name='user',
            name='overdue_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of overdue incidents'),
        ),
    ]
