# Generated by Django 6.0.2 on 2026-02-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Login Failed', 'Login Failed'), ('Register', 'Register'), ('Profile Update', 'Profile Update'), ('Password Changed', 'Password Changed'), ('Item Created', 'Item Created'), ('Item Updated', 'Item Updated'), ('Item Deleted', 'Item Deleted'), ('Request Created', 'Request Created'), ('Request Approved', 'Request Approved'), ('Request Rejected', 'Request Rejected'), ('Item Returned', 'Item Returned'), ('User Created', 'User Created'), ('User Updated', 'User Updated'), ('User Deleted', 'User Deleted'), ('Backup Export', 'Backup Export'), ('Other', 'Other')], max_length=60),
        ),
    ]
