# Generated by Django 6.0.2 on 2026-02-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
