# Generated by Django 6.0.2 on 2026-02-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_returned_at_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='expected_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
