# Generated by Django 6.0.2 on 2026-03-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_request_expected_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
