# Generated by Django 6.0.2 on 2026-04-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_add_is_cleared_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20),
        ),
    ]
