# Generated by Django 6.0.2 on 2026-04-07 16:31

from django.db import migrations


def update_normal_to_medium(apps, schema_editor):
    """Convert existing NORMAL priority values to MEDIUM."""
    Request = apps.get_model('requests', 'Request')
    Request.objects.filter(priority='NORMAL').update(priority='MEDIUM')


def reverse_medium_to_normal(apps, schema_editor):
    """Reverse: convert MEDIUM back to NORMAL."""
    Request = apps.get_model('requests', 'Request')
    Request.objects.filter(priority='MEDIUM').update(priority='NORMAL')


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_change_priority_normal_to_medium'),
    ]

    operations = [
        migrations.RunPython(update_normal_to_medium, reverse_medium_to_normal),
    ]
